### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by johnwc** [zenetys/rpm-haproxy#1]
Do any of the packages have Prometheus metrics support?

**Comment by julthomas** [comment]
Hello John,

Packages are not built with USE_PROMEX=1.
I was considering adding it in 2.7 builds (currently master and haproxy27z+quic branches)... is it what you wish for?

Extract from haproxy Makefile :
```
#   USE_PROMEX           : enable the Prometheus exporter
```

Regards,
Julien T. / ZENETYS

**Comment by johnwc** [comment]
Yes, it would be nice to have a option to install it with Prometheus.

**Comment by julthomas** [comment]
Hello John,
I've made the change, latest 2.7 packages (2.7.5-2) available in our repositories at https://packages.zenetys.com/ were built with USE_PROMEX=1.
Regards,
Julien T. / ZENETYS
