### ISSUE TITLE
License

### ISSUE THREAD

**Issue by UngenuineGuineapig** [zenetys/rpm-haproxy#3]
I've noticed that this repository does not contain any license information. I'm not sure if it applies, but as this seems to be a fork from centos, my guess is that this repository would also need to be licensed under GPLv2, if I'm not mistaken. However, I'm not a lawyer, so this is no legal advice and I might be wrong.

Atleast right now, with no license explicitly declared, this code cannot be redistributed or modified from someone else than you guys, as the standard copyright rules apply: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by julthomas** [comment]
Hello @UngenuineGuineapig,
I have applied GPLv2 license to this RPM spec repository.
Julien

The haproxy RPM spec file in this repository was initially forked from
https://git.centos.org/rpms/haproxy/tree/c8. As per the CentOS Project
Licensing Policy https://www.centos.org/legal/licensing-policy/, GPLv2
license applies to this RPM spec repository.
