### ISSUE TITLE
Prometheus enabled on 2.4

### ISSUE THREAD

**Issue by titansmc** [zenetys/rpm-haproxy#6]
Hi,
I propose to compile it with Prometheus support, I need to stick to v2.4 for now, so that is why I have created https://github.com/zenetys/rpm-haproxy/pull/5

**Comment by titansmc** [comment]
the same for 2.6  https://github.com/zenetys/rpm-haproxy/pull/7

**Comment by julthomas** [comment]
This was merged in branch haproxy24z
